include(${CMAKE_CURRENT_LIST_DIR}/TiffTestCommon.cmake)

set(_ppm "${CMAKE_CURRENT_SOURCE_DIR}/images/rgb-3c-8b.ppm")

foreach(h 1 2)
  foreach(v 1 2)
    foreach(mode strip tile)
      set(_dst "${OUTDIR}/o-addtiffo-${mode}-${h}${v}.tiff")
      if(mode STREQUAL "strip")
        execute_process(COMMAND ${RGB2YCBCR} -c none -r 8 -h ${h} -v ${v} ${_ppm} ${_dst} RESULT_VARIABLE _rv)
        if(_rv)
          message(FATAL_ERROR "rgb2ycbcr failed")
        endif()
      else()
        set(_tmp "${OUTDIR}/tmp-${h}${v}.tiff")
        execute_process(COMMAND ${RGB2YCBCR} -c none -r 8 -h ${h} -v ${v} ${_ppm} ${_tmp} RESULT_VARIABLE _rv)
        if(_rv)
          message(FATAL_ERROR "rgb2ycbcr failed")
        endif()
        execute_process(COMMAND ${TIFFCP} -t -w 16 -l 16 ${_tmp} ${_dst} RESULT_VARIABLE _rv)
        if(_rv)
          message(FATAL_ERROR "tiffcp failed")
        endif()
        file(REMOVE ${_tmp})
      endif()
      execute_process(COMMAND ${ADDTIFFO} ${_dst} RESULT_VARIABLE _rv)
      if(_rv)
        message(FATAL_ERROR "addtiffo failed")
      endif()
      execute_process(COMMAND ${TIFFINFO} -D ${_dst} OUTPUT_VARIABLE _info RESULT_VARIABLE _rv)
      if(_rv)
        message(FATAL_ERROR "tiffinfo failed")
      endif()
      string(REGEX MATCHCOUNT "Directory" _count "${_info}")
      if(_count LESS 2)
        message(FATAL_ERROR "Expected more than one directory for ${_dst}, got ${_count}")
      endif()
    endforeach()
  endforeach()
endforeach()
