set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)
set(CMAKE_C_FLAGS "--sysroot=/usr/x86_64-linux-gnu -msse4.2")
set(CMAKE_CXX_FLAGS "--sysroot=/usr/x86_64-linux-gnu -msse4.2")
set(CMAKE_EXE_LINKER_FLAGS "--sysroot=/usr/x86_64-linux-gnu -L/usr/x86_64-linux-gnu/lib")
set(CMAKE_FIND_ROOT_PATH /usr/x86_64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
